version: '3'

vars:
  QEMU_OPTS: >-
    -m 1024M
    -bios thirdparty/RELEASEX64_OVMF.fd
    -drive format=raw,file=fat:rw:mnt
    -machine q35
    -serial mon:stdio
    -device isa-debug-exit,iobase=0xf4,iosize=0x04
    -nographic
    -no-reboot

includes:
  kernel: 
    taskfile: ./kernel/Taskfile.yml
    dir: ./kernel
  loader:
    taskfile: ./loader/Taskfile.yml
    dir: ./loader

tasks:
  prepare-mnt:
    desc: "Prepare EFI and kernel files"
    cmds:
      - mkdir -p mnt/EFI/BOOT/
      - cp loader/target/x86_64-unknown-uefi/debug/loader.efi mnt/EFI/BOOT/BOOTX64.EFI
      - cp kernel/target/x86_64-unknown-kernel/debug/kernel mnt/kernel.elf

  run:
    desc: "Build and run with QEMU"
    deps: [loader:build, kernel:build]
    cmds:
      - task: prepare-mnt
      - qemu-system-x86_64 {{.QEMU_OPTS}}

  prepare-mnt-test:
    desc: "Prepare EFI and kernel files for test"
    cmds:
      - mkdir -p mnt/EFI/BOOT
      - cp loader/target/x86_64-unknown-uefi/debug/loader.efi mnt/EFI/BOOT/BOOTX64.EFI
      - cp "$(ls -t ./kernel/target/x86_64-unknown-kernel/debug/deps/kernel-* 2>/dev/null | head -n 1)" ./mnt/kernel.elf

  test:
    desc: "Test with QEMU"
    deps: [loader:build, kernel:build-test]
    cmds:
      - task: prepare-mnt-test
      - qemu-system-x86_64 {{.QEMU_OPTS}}

  gdb:
    desc: "Run QEMU with GDB server for debugging"
    deps: [loader:build, kernel:build, prepare-mnt]
    cmds:
      - qemu-system-x86_64 {{.QEMU_OPTS}} -s -S

  debug:
    desc: "Start GDB and connect to QEMU"
    cmds:
      - gdb -q kernel/target/x86_64-unknown-kernel/debug/kernel -ex "target remote :1234"

  fmt:
    desc: "Format code using rustfmt"
    cmds:
      - task: loader:fmt
      - task: kernel:fmt

  clippy:
    desc: "Lint code using clippy"
    cmds:
      - task: loader:clippy
      - task: kernel:clippy

  clean:
    desc: "Clean build artifacts and mnt"
    cmds:
      - task: loader:clean
      - task: kernel:clean
      - rm -rf mnt
